# Generated by Django 5.1.5 on 2025-02-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0003_ingredient_dish_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
